name: Preprocessing Automation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn joblib

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_Daffa-Putera-K.py

      - name: Upload preprocessing output
        uses: actions/upload-artifact@v4
        with:
          name: house_prices_preprocessing
          path: preprocessing/house_prices_preprocessing/
